/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/entity/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity Detail */
        get: operations["entity_detail_entity__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/neighborhood/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Neighborhood */
        get: operations["neighborhood_neighborhood__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Path */
        get: operations["path_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttributeValue
         * @description 属性の1つの値と、それを主張する名前付きグラフの一覧(裁定B82(4a))。
         *
         *     **単数の`graph`ではなく`graphs: list[str]`にする理由**: 同じ値が複数の
         *     名前付きグラフから主張されうる(複数ソースが同じ事実を持つ場合)。
         *     値の行を複製すると、同じ事実を主張する別々の値が2つあるように見える
         *     ——1つの値に対して「それを主張しているグラフの一覧」を持つのが正確
         *     (`Relationship.graph`のキー参照と同じ設計の理由)。**実データで実在を
         *     確認済み**(2026-09-02実測。Fuseki 884,052クアッド。`org:cityName`・
         *     `org:houjinBangou`等が`houjin-bangou`と`houjin-bangou-payees`のように
         *     別の名前付きグラフから同じ値を主張する組が実在する。
         *     `queries.py`の`_build_attributes_query`docstring参照)。
         */
        AttributeValue: {
            /** Graphs */
            graphs: string[];
            /** Value */
            value: string;
        };
        /** EntityDetailResponse */
        EntityDetailResponse: {
            /** Attributes */
            attributes: {
                [key: string]: components["schemas"]["AttributeValue"][];
            };
            /** Graphs */
            graphs: {
                [key: string]: components["schemas"]["Provenance"];
            };
            /** Id */
            id: string;
            /** Id Path */
            id_path: string;
            /** Label */
            label: string | null;
            /** Relationships */
            relationships: {
                [key: string]: components["schemas"]["Relationship"][];
            };
            /** Relationships Limit */
            relationships_limit: number;
            /** Relationships Truncated */
            relationships_truncated: boolean;
            /** Type */
            type: string;
        };
        /**
         * EntityRef
         * @description 一覧・関係に出す最小限のエンティティ参照。
         */
        EntityRef: {
            /** Id */
            id: string;
            /** Id Path */
            id_path: string;
            /** Label */
            label: string | null;
            /** Type */
            type: string;
        };
        /**
         * GraphEdge
         * @description 近傍サブグラフ・パス探索の辺1本。
         *
         *     **`Relationship`と別の型にする理由**: `Relationship`は「あるエンティティ
         *     から見た関係」なので`direction`(自分が主語か目的語か)を持つ。
         *     サブグラフの辺は**特定の視点を持たない**ので、代わりに`source`/`target`
         *     (どちらも完全IRI)で向きを表す。`direction`を流用すると「誰から見た
         *     向きなのか」が応答から読めなくなる。
         */
        GraphEdge: {
            /** Graph */
            graph: string;
            /** Predicate */
            predicate: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * NeighborhoodResponse
         * @description 近傍サブグラフ(仕様§9.1「指定ノードから深さ1-2のノード/エッジ」)。
         *
         *     **既知の限界(観察O10)**: `LawRevision`(実データで9,550件)は
         *     **グラフの辺を1本も持たない** —— 法令への結びつきは`lawId`という
         *     リテラルとIRIのパスに埋まった法令IDだけで、辺として存在しない。
         *     **したがって法令の近傍に改正は一度も現れない。**
         *     利用者が「この法令の近傍にはこれしか無い」と読むのは誤りである
         *     (辺を足すのはPhase 2の課題)。**黙っていないためにここに書く**
         *     (このプロジェクトの再発欠陥6: 報告が嘘をつく)。
         */
        NeighborhoodResponse: {
            center: components["schemas"]["EntityRef"];
            /** Depth */
            depth: number;
            /** Edge Limit */
            edge_limit: number;
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Edges Truncated */
            edges_truncated: boolean;
            /** Fanout Limit */
            fanout_limit: number;
            /** Fanout Truncated Nodes */
            fanout_truncated_nodes: string[];
            /** Graphs */
            graphs: {
                [key: string]: components["schemas"]["Provenance"];
            };
            /** Node Limit */
            node_limit: number;
            /** Nodes */
            nodes: components["schemas"]["EntityRef"][];
            /** Nodes Truncated */
            nodes_truncated: boolean;
        };
        /**
         * PathResponse
         * @description パス探索(仕様§9.1「2エンティティ間の経路(法令↔法人など)」)。
         *
         *     **`found=False`の読み方を応答の形で強制する。**
         *     「max_depth以内に経路が無かった」と「経路が存在しない」は違う ——
         *     空の結果だけを返すと利用者は後者だと読む(このプロジェクトが繰り返し
         *     重い欠陥として扱ってきた「報告が嘘をつく」型)。`exhaustive`が真で
         *     初めて後者を意味する。
         */
        PathResponse: {
            /** Budget Exhausted */
            budget_exhausted: boolean;
            /** Depth Limited */
            depth_limited: boolean;
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Exhaustive */
            exhaustive: boolean;
            /** Fanout Limit */
            fanout_limit: number;
            /** Fanout Truncated */
            fanout_truncated: boolean;
            /** Found */
            found: boolean;
            goal: components["schemas"]["EntityRef"];
            /** Graphs */
            graphs: {
                [key: string]: components["schemas"]["Provenance"];
            };
            /** Max Depth */
            max_depth: number;
            /** Nodes */
            nodes: components["schemas"]["EntityRef"][];
            /** Searched Depth */
            searched_depth: number;
            start: components["schemas"]["EntityRef"];
            /** Undirected */
            undirected: boolean;
            /** Visit Budget */
            visit_budget: number;
            /** Visited */
            visited: number;
        };
        /**
         * Provenance
         * @description CQ7(`queries/cq/cq07-provenance-of-edge.rq`)と同じ3項+グラフ自身。
         */
        Provenance: {
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Fetched On */
            fetched_on: string;
            /** Graph */
            graph: string;
            /** License */
            license: string;
            /** Source */
            source: string;
        };
        /**
         * Relationship
         * @description エンティティ詳細の関係1件。
         */
        Relationship: {
            /** Direction */
            direction: string;
            /** Graph */
            graph: string;
            /** Predicate */
            predicate: string;
            related: components["schemas"]["EntityRef"];
        };
        /**
         * SearchHit
         * @description 検索結果の1件。`summary`だけが検索固有(エンティティ詳細には出さない)。
         */
        SearchHit: {
            /** Id */
            id: string;
            /** Id Path */
            id_path: string;
            /** Label */
            label: string | null;
            /** Summary */
            summary: string | null;
            /** Type */
            type: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Limit */
            limit: number;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchHit"][];
            /** Truncated */
            truncated: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    entity_detail_entity__entity_id__get: {
        parameters: {
            query?: {
                /** @description 関係一覧の既定50・最大200。超過は422で拒否する */
                limit?: number;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    neighborhood_neighborhood__entity_id__get: {
        parameters: {
            query?: {
                /** @description 深さ。既定1・最大2(仕様§9.1が「深さ1-2」と定めている)。超過は422で拒否する(黙って丸めない) */
                depth?: number;
                /** @description 総ノード数の上限。既定100・最大500 */
                node_limit?: number;
                /** @description 総エッジ数の上限。既定200・最大1000 */
                edge_limit?: number;
                /** @description **1ノードあたりの分岐数の上限。** 総数の上限だけではハブ1個が予算を食い潰し、他の方向が1つも見えなくなる(既定25・最大100) */
                fanout_limit?: number;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeighborhoodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    path_path_get: {
        parameters: {
            query: {
                /** @description 始点の`id_path`(`/entity/`と同じ形) */
                from: string;
                /** @description 終点の`id_path`(`/entity/`と同じ形) */
                to: string;
                /** @description 探索の深さ。既定4(法令→府省→事業→支出→法人の縦スライスが4ホップ)・最大6。超過は422で拒否する */
                max_depth?: number;
                /** @description 訪問ノード数の予算。既定400・最大2000。**使い切ったら`budget_exhausted`が真になり、`found=false`は「無い」ではなく「見つからなかった」を意味する** */
                visit_budget?: number;
                /** @description 1ノードあたりの分岐数の上限。既定50・最大200。**これが効くと探索は不完全になり`exhaustive`は真になれない** */
                fanout_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                /** @description 検索語(部分一致・大文字小文字を無視) */
                q: string;
                /** @description 既定20・最大100。超過は422で拒否する(黙って丸めない。queries.pyのコメント参照) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
