# CQ P0-3: ある関係は、どの一次資料の何日取得分に基づくか
PREFIX prov:    <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX org:     <https://jgkg.norr-tech.com/def/org#>

SELECT ?graph ?source ?fetchedOn ?license WHERE {
  GRAPH ?graph { ?s org:houjinBangou "6000012070001" }
  ?graph prov:wasDerivedFrom ?source ;
         prov:generatedAtTime ?fetchedOn ;
         dcterms:rights ?license .
}
